### ISSUE TITLE
[NOTICE] The future of this library - COMPLETED!!

### ISSUE THREAD

**Issue by tripflex** [tripflex/wifi-captive-portal#3]
So after discussion regarding this library (https://forum.mongoose-os.com/discussion/2702/library-wifi-captive-portal-web-ui-list-ssids-test-configure-rpc-gzip-support) I think the best thing to do is to look at separating the functionality into multiple libs.  

This will help keep bloat on projects to a minimum, and prevent this lib from being one large monolithic library that users may not need all included functionality for.

## TODO

- [x] Create captive portal library, specifically for serving DNS and HTTP (to allow users to use their own HTML/JS/CSS)
- [x] Create wifi captive portal library, which ports just the HTML/JS/CSS and GZIP functionality to it's own lib, using the captive portal lib as a dep
- [x] Create RPC library, to port over RPC handling to its own lib, so if users only need the RPC endpoints ,they can have that
- [x] YOUR IDEA!?  Comment on here and let me know!

**Comment by tripflex** [comment]
@MydevOnline ahhhhh that's actually not a bad idea at all!   I know mamuesp has released a timezone lib for handling timezone data, and we had discussed options for setting lat/long but i think this would be a good option to have as another way of setting these values

**Comment by tripflex** [comment]
Still a work in progress but these will be the new libraries:
https://github.com/tripflex/captive-portal
https://github.com/tripflex/captive-portal-wifi-web
https://github.com/tripflex/captive-portal-wifi-rpc

And this will be the new full stack library:
https://github.com/tripflex/captive-portal-wifi-stack
